import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { API_BASE_URL } from "./lib/config";
import { cookies, headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Focus Flow",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  let user = null;
  try {
    const cookieStore = await cookies();
    user = await fetch(`${API_BASE_URL}/auth/user`, {
      cache: 'no-store',
      // Next.js automatically forwards incoming cookies to your API if configured,
      // or you can explicitly pass cookies() from 'next/headers'
      headers: {
        Cookie: cookieStore.toString(), // Safely forwards the HttpOnly token cookie to Express
      },

      credentials: 'include',
    });
    user = await user.json();
    if (!user.success) {
      user = null;
    }
    console.log("User data fetched from API: on layout", user);
  } catch (error) {
    // Handle unauthenticated state / redirect to login
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header user={user} />
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
